[tool.pyright]
venvPath = "."
venv = ".venv"

[tool.ruff]
line-length = 100


[project]
name = "sector-constrained-portfolio"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.0",
    "ipykernel>=7.2.0",
    "jupyter>=1.1.1",
    "lxml>=5.1.0",
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "pandas>=3.0.1",
    "pyswarm>=0.6",
    "requests>=2.32.0",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.1",
    "seaborn>=0.13.2",
    "yfinance>=1.2.0",
]
